**❓ What is NumPy**

NumPy is a high performance numerical library that gives Python the power to work with large datasets efficiently. It provides fast, memory optimized arrays and mathematical tools that form the core of every machine learning workflow.

**⚙️ Why NumPy is Important in Machine Learning**

NumPy (Numerical Python) is the **foundation of all Machine Learning libraries in Python**.  
Almost every ML library — including Pandas, Scikit-Learn, TensorFlow, and PyTorch — is built on top of NumPy.

**🔍 Why It’s Essential**
- 🧮 **Efficient Computation:** Handles large numerical datasets faster than Python lists.
- 🧱 **Data Representation:** ML data (features & labels) are stored as matrices/tensors → NumPy arrays.
- ⚙️ **Vectorization:** Executes math operations on entire arrays without loops.
- 🔢 **Linear Algebra Support:** Used in gradient descent, covariance, matrix multiplication, etc.
- 🤝 **Integration:** Works seamlessly with Pandas, Matplotlib, Scikit-Learn, TensorFlow, and others.

> 💡 *If Python is the language of Machine Learning, NumPy is its mathematics engine.*

---

### Install and import Numpy lib 

In [1]:
%pip install numpy==2.3.5


[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.3.5


### Compare list and numpy Array


In [4]:
import time 
import numpy as np

n = 1000000

py_list = list(range(n))
np_array = np.array(py_list)

print(len(py_list))   
print(len(np_array))

print(py_list[:5])
print(np_array[:5])

# python list
t1 = time.time()
py_ressult = [x * 2 for x in py_list]  # multiplying each element by 2
t2 = time.time()

# Numpy array (Same operation)
t3 = time.time()
np_result = np_array * 2  # multiplying each element by 2
t4 = time.time()

print("List time:", t2 - t1)
print("Numpy array time:", t4 - t3)


1000000
1000000
[0, 1, 2, 3, 4]
[0 1 2 3 4]
List time: 0.024981975555419922
Numpy array time: 0.009922027587890625


In [5]:
a = []

for x in py_list:
    a.append(x * 2) 

print(len(a))
print(a[:5])
print(py_list[:5])

1000000
[0, 2, 4, 6, 8]
[0, 1, 2, 3, 4]


### creating a Numpy Array

In [6]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])

arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,23]]])

print("1D array:", arr1)  # vectors 
print("2D array:\n", arr2)  # matrices
print("3D array:\n", arr3)  # tensors


1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 23]]]


In [7]:
print(type(arr1))

<class 'numpy.ndarray'>


In [8]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
# Array attributes
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)
print("Shape of arr3:", arr3.shape)

print("Dimensions of arr1:", arr1.ndim)
print("Dimensions of arr2:", arr2.ndim)
print("Dimensions of arr3:", arr3.ndim)

print("Data type of arr1:", arr1.dtype)
print("Data type of arr2:", arr2.dtype)
print("Data type of arr3:", arr3.dtype)

print("Total elements in arr1:", arr1.size)
print("Total elements in arr2:", arr2.size)
print("Total elements in arr3:", arr3.size)

Shape of arr1: (5,)
Shape of arr2: (2, 3)
Shape of arr3: (2, 2, 3)
Dimensions of arr1: 1
Dimensions of arr2: 2
Dimensions of arr3: 3
Data type of arr1: int64
Data type of arr2: int64
Data type of arr3: int64
Total elements in arr1: 5
Total elements in arr2: 6
Total elements in arr3: 12


### creating a specila type of Arrays 

In [10]:
zeros = np.zeros((3, 3))
print("Zeros array:\n", zeros)
ones = np.ones((2, 4))
print("----------------------------")
print("Ones array:\n", ones)
identity = np.eye(4)
print("----------------------------")
print("Identity matrix:\n", identity)


rangeArray = np.arange(0, 10, 2)  # start, stop, step 
print("Range array:", rangeArray)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------------------
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
----------------------------
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Range array: [0 2 4 6 8]


### inedxing & Slicing 

In [11]:
arr = np.array([
  [10, 20, 30],
  [40, 50, 60],
  [70, 80, 90]
])
print("Original array:\n", arr)
print("Shape:", arr.shape)


print(arr[0,1]) #Accessing element at row 0, column 1 (20)
print(arr[1])   # Accessing the entire second row ([40, 50, 60])
print(arr[:, 2]) # Accessing the entire third column ([30, 60, 90])

Original array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
20
[40 50 60]
[30 60 90]


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b =", a + b)  # Element-wise addition
print("a - b =", a - b)  # Element-wise subtraction
print("a * b =", a * b)  # Element-wise multiplication
print("a / b =", a / b)  # Element-wise division
print("a ** 2 =", a ** 2)  # Element-wise exponentiation



a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** 2 = [1 4 9]


### Reshaping & Flattening

In [13]:
arr = np.arange(1, 10)
reshapped = arr.reshape(3, 3)
flattened = reshapped.flatten()

print(arr)
print("-----")
print(reshapped)
print("-----")
print(flattened)

[1 2 3 4 5 6 7 8 9]
-----
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----
[1 2 3 4 5 6 7 8 9]
